### ISSUE TITLE
need a branch for Plone5.2.x

### ISSUE THREAD

**Issue by adam139** [collective/Products.membrane#17]
need a branch for Plone5.2.x
drop Archetypes support

**Comment by agitator** [comment]
Feel free to create one and start working on it ;-)
There are most probably some people that depend on this addon, including me

**Comment by mauritsvanrees** [comment]
It may be better to start from scratch with a new add-on that does not have the ancient heritage of Products.membrane.  See also issue #4.

For content as groups in Plone 5.2, I recently created [collective.contentgroups](https://github.com/collective/collective.contentgroups). For users, a similar package would be needed. (I only needed groups in my use case.)

But yes, a branch where AT support is removed, can help for current users of this package. Or perhaps better, or as a first step: make AT support optional, so that `Products.Archetypes` is not pulled in. A start would be to add a `zcml:condition="installed Products.Archetypes"` around `<include package=".at" />`,  but more is likely needed.

**Comment by agitator** [comment]
I like the idea of starting a membrane add-on from scratch and Plone 5.2 would be a good moment for that.

I talked with @jensens and we came up with the following proposal:
- user/group content/behavior based on dexterity
- use approval workflow from dexterity.membrane
- PAS plugins: copy Products.Membrane if makes sense, else start over fresh.
- Python 3.6+ only
- drop membrane_tool in favor of portal_catalog
- simplify to base features - candy can come in additional add ons.
- support for self-registration, password reset, ... as known in Plone
- respect settings for email or uuid as username from Plone

Additional:
- upgrade step for dexterity.membrane types?
- upgrade step for Products.remember (AT) types?

The project I have that uses dexterity.membrane and therefore Products.membrane has a lot of other add-ons that have to be upgraded and budget is tight as it is probably for most projects.

Therefore the question, who else depends on functionality like this and is willing to chip in?

@adam139 @ale-rt @cedricmessiant @djowett @gyst @ksuess @mauritsvanrees @pilz @vincentfretin

**Comment by mauritsvanrees** [comment]
I don't currently use membrane.

I would use collective.contentgroups and use the same approach for a separate contentusers package. The biggest work here is writing the [adapter](https://github.com/collective/collective.contentgroups/blob/master/src/collective/contentgroups/adapters.py) to implement various methods from lots of interfaces. For the groups, it needed to function like: PloneGroup, PloneUser, PropertiedUser. IGroupData, IManageCapabilities. The adapter has methods that are defined properly in interfaces, but also other methods that were needed in practice.
Various functions could have been inherited from base classes, but for clarity I implemented them all myself (or maybe almost all) and only used BasicUser as base class. This avoid having functions that may come from ten different classes, which is one of the reasons membrane is so hard to understand.

For the plugins, I'd say start fresh, though having a good look at current membrane is of course useful. For the [groups plugins](https://github.com/collective/collective.contentgroups/blob/master/src/collective/contentgroups/plugins.py) I didn't need much.

I started with Python 3.6. Python 2.7 happened to work without changes.

Possibly a third package could be made that combines contentgroups and contentusers in an opinionated way. It defines Group and User portal types, and lets them use approval workflow. Maybe that is even the only code that needs to be here. It can serve as an example for people that want to create their own types through the web.

membrane_tool must indeed die, and we can use portal_catalog. But for performance, and to avoid adding lots of indexes (see [`membrane_tool.xml`](https://github.com/collective/Products.membrane/blob/master/Products/membrane/profiles/default/membrane_tool.xml)), we could add a utility much like the redirection tool. We would have several BTrees there with mappings from login to user id and back, user id to group, etcetera. Some event handlers are needed to keep this information current.  The canonical place for this information would be the content users and groups, or other parts of PAS. The utility would just be a more performant way of getting the information.

The authentication part, and especially email as login, are going to be tricky.

**Comment by ksuess** [comment]
I am interested and would be glad to contribute.
Your requirements sound reasonable.

**Comment by pilz** [comment]
We are currently working on making ploneintranet py3 compliant. Products.Membrane will be a part of that. We discussed internally and in the ideal world, we love the approach to rewrite and we would like to participate. 
However, we are forced by a customer to be complete with the py3 switch by 31.12. and having a rewrite ready and to the necessary migrations is a bit scary.
We will probably therefore also start a plone5.2 branch on Products.membrane and do a by-the-book upgrade in parallel.

**Comment by ale-rt** [comment]
Now master is Plone5.2 ready.
Also dexterity.membrane master is Plone5.2 ready.
It would be good to have a major release.

**Comment by ale-rt** [comment]
BTW I can do that as well if I am added as package maintainer on PyPI (my account is `alert`)

**Comment by mauritsvanrees** [comment]
@ale-rt I have added you as PyPI owner to Products.membrane and dexterity.membrane. And for good measure also to the old Products.remember.

**Comment by ale-rt** [comment]
Thanks!
