### ISSUE TITLE
Unable to install membrane through buildout

### ISSUE THREAD

**Issue by marfago** [collective/Products.membrane#6]
I've just added Product.remember and Product.membrane to my buildout.cfg (in both sections, eggs and zcml), but I have this error:

Getting distribution for 'Products.membrane'.
error: [Errno 2] No such file or directory: 'README.txt'
An error occurred when trying to install Products.membrane 2.1.12. Look above this message for any errors that were output by easy_install.

Any hints?

**Comment by hvelarde** [comment]
smae issue over here; @mauritsvanrees the release is broken, would you mind creating a new one?

**Comment by hvelarde** [comment]
@mauritsvanrees I fixed the issue inhttps://github.com/collective/Products.membrane/commit/93bf0a29a5ea580b3a9d7c0f324955e4ede00658 a new release will be truly appreciated.

**Comment by mauritsvanrees** [comment]
Ah, that error again, with the broken symlink behaviour...
I have released 2.1.13.
Thanks for the report, @marfago.
And thanks for the fix, @hvelarde.
